name = "Phantoms"
uuid = "9bf6ac95-9ecd-4b40-9903-3771e8d4f0b8"
authors = ["Dale-Black <djblack@uci.edu> and contributors"]
version = "0.1.0"

[deps]
TestSetExtensions = "98d24dd4-01ad-11ea-1b02-c9a08f80db04"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
